### ISSUE TITLE
Upgrade Notes

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1062]
Add Date and Time
Add photo upload option
This photo will be attached to the note entry.

**Comment by damirius** [comment]
@bsaiken 
We are talking here about mobile/notes page right? We already show date and time with the note there.
I'll add photo upload option since I'm fixing that bug with adding new notes currently.

**Comment by bsaiken** [comment]
This would affect `mobile/notes` and `/activetask/showForm`.

**Comment by damirius** [comment]
@bsaiken 

OK. Didn't even know that we have notes on activetask/showForm page since I didn't add them there so I didn't notice that they aren't displaying date and time like mobile notes.
I'll add photo upload on both pages and I'll add date and time for /activetask/showForm

**Comment by bsaiken** [comment]
@damirius 
> Damir wrote:
I'll add photo upload on both pages and I'll add date and time for /activetask/showForm

Note the related Issue #1063

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

I've added photo upload for both mobile notes and active task notes for PM. Also date and time should be displayed on active task page in a same way as on mobile notes page.
On message display urls will be hyperlinked and if you click them image should open in a new tab. 

Just want to note that we can use refresh here to check for FT's notes on active task page because `executeGetNotes` method in `ActiveTaskController` also makes direct query to the db instead to the session just like discussions.

Like always you can see changes on feature_damir branch

**Comment by bsaiken** [comment]
@damirius 
This does work.  It resulted in a new Issue for you - #1157.  Which, due to it's similarity, should be fairly quick to implement.
