### ISSUE TITLE
We are still getting phantom forms when a Task is activated.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1065]
Login under "baiken" and look at task_id=12, forms.  There were no forms identified for this Task, and the file "bedroom organization.png" appears.

**Comment by WebDevJL** [comment]
@bsaiken 

Verifying if related to #1117.

**Comment by bsaiken** [comment]
@WebDevJL 
It is likely.  I just create a new Task last night, one with no forms, and this same photo "Bypass" appeared in the forms list.

**Comment by WebDevJL** [comment]
For info @damirius 
@bsaiken 

Actually, the problem wasn't related at all. Instead, we were getting the task locations and all the documents and trying to match all the documents to the `task_location_id` list. But in that case, we weren't filtering on the `document_category`.
So, the `task_id=12` had a `task_location_id=52` and a document of `location_id=52` was matched to it, hence the result showing in the task forms list.

In order to limit the amount of data queried and fix the bug, I have made the change so we only return task_location documents so that the matching condition is always correct.

**Comment by WebDevJL** [comment]
@bsaiken 

Also, I see now that we need a new column in the document table: document_category_id_value (e.g. in the case [above](https://github.com/FWAJL/FieldWorkManager/issues/1065#issuecomment-125860052) document_category = task_location_id and document_category_id_value = 52).
In fact, we store the document_category_id_value is the document_value but having in a standalone column in addition to that means we can query it more easily and more efficiently than on the document_value.

Can you create the issue if you think it is worth doing it?

Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
It is good to know the problem, and that it is party fixed.  However, I'm sure you can see this is a Very Low Priority item, so we will come back to it if we can get the other Issues resolved.

**Comment by WebDevJL** [comment]
@bsaiken 

Yes, I noticed the priority. However, this issue 1065 will be closed soon (after 1.7.4 release).
Can we create the issue for the document table improvement still?
Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
Now, when I activate a Task, we do not get any task forms created.  We will need to put this on the backburner since we are focusing  on Webforms.

**Comment by WebDevJL** [comment]
@bsaiken

It is not related to this issue. This issue was happening in the active
task section.

Forms not being created is in the task edition section, more specifically
when we activate it.

Can you please create a new issue? Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
I will make a new Issue then.  It may well be that we temporarily disabled this feature and I forgot.
