### ISSUE TITLE
Activate geolocation for the FT UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1070]
This should be automatically accessed when the FT clicks the button to "Mark" a location.

See also Issue #1079 - adding locations should also automatically access Geo-location.  Add code to that developed for 1079 asking the FT if they would like to use their current coordinates.

More info available at #1087.

**Comment by WebDevJL** [comment]
@bsaiken 

I don't understand what you want here.

**Comment by bsaiken** [comment]
@WebDevJL 
What I want is the correct coordinates when marking a location in the field.  

I tried to "Mark" locations in the field with my iPhone.  

<img width="1440" alt="screen shot 2015-07-07 at 9 01 59 am" src="https://cloud.githubusercontent.com/assets/8228624/8547809/ec2b1bd6-2486-11e5-8427-1691e17daa2a.png">

Sometimes, the coordinates were WAY off.  I think that is because the mobile device is keeping track of it's last known position.  This could be the nearest cell phone tower (or something, I don't know).  So, if I use a standard mapping APP, like Google Maps, or Apple's map APP

![img_3321](https://cloud.githubusercontent.com/assets/8228624/8548135/ae9a18d8-2488-11e5-865e-d1b4ded47d6f.PNG)

Then I can use the target to set the phone's coordinates.

https://support.google.com/gmm/answer/3137748

![img_3322](https://cloud.githubusercontent.com/assets/8228624/8548308/b5e328f4-2489-11e5-89d1-67ce5a28caf9.PNG)

**Comment by bsaiken** [comment]
>@FWAJL said:
The Google Maps services includes a Geolocation API that uses cell towers, wifi hotspots positions or GPS to calculate yours.
When using our web interface, we don't have the Geolocation active (see the icon you circled in the last image of #1070). We should add a button that when clicked will ask permission to request coordinates and then the data will call the Google Maps to load the location retrieved. That's the theory.
Also, 4G network QOS does matter a lot in the accuracy if not using GPS!

We don't need to add a button, we already have one.  If the user clicks "Mark" from the mobile map info window, they are requesting the coordinates.

**Comment by bsaiken** [comment]
@damirius 
The correct coordinates would be fetched by clicking "Mark", or when we the FT adds a new location, as we just completed for Issue #1079.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

If I'm correct we want to use current coordinates (same as "mark") of FT when he adds new location through location list page right? Since mark option should already work on the map page.
It will work if FTs use GPS for geolocation, if not, like you said, coordinates can be off by a huge margin.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
> If I'm correct we want to use current coordinates (same as "mark") of FT when he adds new location through location list page right?

Yes

> It will work *if* FTs use GPS for geolocation, *if not*, like you said, coordinates can be off by a huge margin.

There is no "if" here.  In order for the tool to be effective, we *MUST* have accurate coordinates.   Specify what conditions must be met in order to ensure that FTs are using geolocaiton.  This is not a random set of web users, these are highly compensated professionals, and they will follow guidelines we provide, even if it means having a certain type of mobile device or a certain type of internet service (e.g. 4G).

**Comment by damirius** [comment]
@bsaiken @FWAJL 

OK, I've added mark button in "Add new location" infowindow on location list, it works the same as on the mobile task map.
There are few options that I've added there, we can specify if we want to use cached locations and how old that cache can be. I turned that off, it's set to 0, so every time FT clicks 'Mark' button, api will try to fetch new coordinates. There's also `enableHighAccuracy` option which will try to get most accurate coordinates, note that this forces web app to prioritize accuracy over speed of the response but it doesn't force user's device to use GPS or something more accurate if that user have their GPS turned off. So FT's still need to have their high accuracy locating set on their devices, there's no way around that.
`getCurrentPosition` built in function which we use returns `position` object. That position object contains `coordinates` object which we use to get `latitude` and `longitude`, it contains few other properties like `speed` and some other stuff, but it also contains property called `accuracy`. That property will return estimated accuracy in meters. I've tested it for a bit there. From my desktop PC I get ~10km (~6.21 miles) which is right I guess, since I'm connected to my router over LAN and I use ADSL, so geolocator best guess is my IP range. 
Then I used my android phone. There are 3 "location mode" options, 'High Accuracy' which uses GPS, WiFi and cellular networks, 'Battery saving' which uses only WiFi and cellular networks and 'Device only' which just uses GPS.
Inside I got accuracy of 30m(~100feet) for both 'High Accuracy' and 'Battery saving' modes.
Outside I got 10m(~30feet) accuracy on 'High Accuracy' mode and 30m(~100feet) on 'Battery saving` mode. I couldn't walk too far since I had to stay connected on my WiFi router to be able to access the app over network.
So we can maybe make a check before loading coordinates to see if accuracy is less than 30 meters or something like that if you wish. If it's less than 30meters we populate lat/lng fields if not we just leave them empty and show them some message that 'We can't fetch accurate coordinates' or something like that.

New commit (without accuracy check) is on feature_damir branch like always.

**Comment by bsaiken** [comment]
@damirius 

Thanks Damir.  This is good information.  The bottom line is we need best accuracy, even if it takes a "long time".  If a FT must wait 60 seconds while marking a location, that is actually, in the grand scheme of things, a huge time saver.  So, the concept of "speed" is entirely relative.
In most cases, Wifi will NOT be available, so we have to rely on the mobile device.  
I know there must be very accurate GPS information available, even without Wifi.  When I use any mobile device mapping tool, I can see the blinking blue dot, representing my position, is almost always very accurate (<< 10m).  There are also apps, like "GPS Location" by Acceleroto, which give very accurate coordinates and even fairly accurate elevation values.  Due to the nature of my work, this is a critical item.

That being said, per my post above, from a prior field test, I could ALWAYS got acceptably accurate coordinates.  But, I would need to perform the follow these steps:
1) open a mapping tool, like Google maps
2) click on the target button
3) return to the website *then* mark the location

My question was, can we instruct the mobile device, through our website's coding, to take the same action that the target button does?  If yes, we must do it.  If no, we must tell the user about the additional required steps.

Finally, it will come down to testing on my end, since accuracy in the US may be very different than where you are.

One more request: please add a re-direct to the map page after adding a new location so the FT can see if the location was placed correctly.

**Comment by damirius** [comment]
@bsaiken 

I've pushed new commit which fixed some bug with saving coordinates and I added redirect to map page after user adds new task location on the list.

I'll test everything out for marking and get back to you with some videos.

**Comment by bsaiken** [comment]
@damirius @FWAJL 

There are many problems.  
* First, refreshing the page `/activetask/map` does not show the new locations added by the FT.  I have to log out and log in to see the new locations.  This must be changed.  
* The menu item "Mark" is missing from the Location List location info window.  Therefore, I am no longer able to mark Locations.  These are Locations entered by the PM, assigned to the task, but do not yet have coordinates.
* The info window I see when I click "Add New Location" is wrong.  This shows the Latitude and Longitude fields - it should not.  
* I think the code for the two info windows conflict because now the "Add New Location" info window does not show the "Mark" option, and it did before.  We should not need the "Mark" button, this should be automatic.
* If I refresh the page using the smartphone, after the PM makes changes to the Locations for the task, the information is displayed incorrectly.  In the photo below, I had deleted (as PM) all Locations except APT2, but the deleted locations show up as "Other Project Locations".

![mobile photo after location delete](https://cloud.githubusercontent.com/assets/8228624/9066268/33cf7a1a-3a9c-11e5-94fa-25287e114e24.jpg)

**Comment by bsaiken** [comment]
@damirius 
OK - with your update the location coordinaes I got, when I saved after clicking the "Mark" button, was spot on.  This requires some additional testing, which I will do today.  But the other Issues I pointed out also need to be fixed.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

New commit on feature_damir branch.

There's no conflict between infowindows. I thought that we wanted to add Mark button to new location infowindow so that FT can edit coordinates manually if he doesn't want to add them automatically through geolocator. I've removed both latitude/longitude fields together with mark button.
I've also added mark button back to existing location infowindows so FT's can edit existing locations without coordinates in the list.

OK, moving on. I saw your new comment now, but I was already doing some tests to compare geolocation on google maps with our map to see if there is any difference.
Here is the screencast from my desktop pc: https://drive.google.com/file/d/0B7Laiv0PjSvDQ2dqS0ZhYzg1Nkk/view
I've done this before I hid lat/lng fields, now we don't need to click on 'Mark' button before saving this will be done automatically, but it's the same process.
You can see that both google maps geolocator and our geolocator show the same (wrong) coordinates. They should show coordinates for Tesla, Pancevo but instead they are showing Belgrade. Like I said they are probably using IP range and my ISP is registered in Belgrade so I guess that's the location they have for them.
I've also recorded my phone screen and did the same test. 'High accuracy' mode was on so GPS was used.
Here's the video: https://drive.google.com/file/d/0B7Laiv0PjSvDSlFXQWhtY2xHRU0/view
Using GPS, both google maps and our geolocator fetched more accurate coordinates and they are again the same.

For other points, this problem is bigger then most of the stuff here. I mentioned that few months earlier I think. We will have problems if some piece of data can be modified by multiple users in the same time.
When the user logs in, any user type (FT/PM), and he visits some page with data, let's say locations, we will fetch everything and store it in sessions. After that everything that is modified will be stored in DB and in Session, but that user will not read anything related to locations from the DB just from his Session. So editing some location as FT can't be seen by his PM or other FTs if they are logged in already, they have to log out and log in again so that script refreshes their session from the DB. Of course user can't access session of another user so there's that. 
Here is the simple diagram: 
![sessiondb](https://cloud.githubusercontent.com/assets/1443969/9068280/dda33568-3ae2-11e5-882a-b5e4e9734ece.png)

**Comment by bsaiken** [comment]
@damirius 
This looks good.  However, the only way for me to do a proper function test is to do it in the field, so the code must be released to the DEV branch.  

As far as the Session arrays go, we will need to make a new Issue to manage that.
