### ISSUE TITLE
Remove contextual menu from analyte/uploadList for common analytes

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1114]

**Comment by FWAJL** [comment]
@bsaiken 

When editing a field paramater from the analyte/listAll view, the check "IsfieldAnalyteExisting" is not working because you removed resource in the commit  fa50574589cd0ea2de96ebddb44bd4d1ebef4397 and also, the check is failing ("message_error_isfieldAnalyteExisting").

See details below:
![screen shot 2015-07-27 at 05 52 03](https://cloud.githubusercontent.com/assets/7524388/8898394/ddbe8ffe-3423-11e5-864e-f0c2bf22e92c.png)

**Comment by bsaiken** [comment]
@FWAJL 
I'm way ahead of you.
https://github.com/FWAJL/FieldWorkManager/commit/b5431ebffb6cbfde12f34c0bedda40859a4eef45
