### ISSUE TITLE
Photo uploading has an undetermined error

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1117]
Log onto PM user "baiken".  Under the Project "Job Hunting", choose Map > All Project's Locations
You can access all users with the "admin" login, but you may need to email me to get the updated password.

Then select "Location 1" and bring up the info window.  There is one stored photo.

<img width="1440" alt="screen shot 2015-07-27 at 8 23 59 am" src="https://cloud.githubusercontent.com/assets/8228624/8907116/81d8275c-3439-11e5-8328-5c560635b9fe.png">

This is the photo I see when I click the link.

<img width="1440" alt="screen shot 2015-07-27 at 8 23 50 am" src="https://cloud.githubusercontent.com/assets/8228624/8907085/4efb7046-3439-11e5-8e9e-15bdc418e211.png">

I am absolutely certain I did not upload this photo under this Project, Task, Location.  I uploaded it under the Project > Task > Location: El Campo > System Check > Treatment Stub.  And, indeed, that is where it is.

Why is this photo showing up where it is not supposed to?  This is a critical flaw.

**Comment by FWAJL** [comment]
@bsaiken 

I have identified the document representing this photo. It is indeed part of the location 134 in the project 14 (El Campo). I will extract the DB from live server and debug locally to see why the Job Hunting retrieves that document for the Location 1 (id=13)

**Comment by WebDevJL** [comment]
For info @damirius @gsouvik 

@bsaiken 

Bug resolved. It is very possible that it resolves the phantom forms as well since they are documents. It only happens in some specific case like the one below. Nice job creating the hard-to-replicate case!

The problem was in the sql query where a "_" was used and it is a [wildcard](http://stackoverflow.com/questions/8236818/why-does-underscore-match-hyphen).

So the query to get location photos for location 13

`SELECT d.* FROM `document` d where d.`document_category` = 'location_id' and d.`document_value` LIKE '13_%'; `

was returning the photo for location 134 because of the _ before the % (also a wildcard in sql).

The correct query is :

 `SELECT d.* FROM `document` d where d.`document_category` = 'location_id' and d.`document_value` LIKE '13\_%';`

**Comment by bsaiken** [comment]
@FWAJL 
I am going to clear this one without extensive testing, because I am not certain I could create the required conditions, so we will need to see how it goes as I continue alpha testing.
