### ISSUE TITLE
Merge #1133: conflict in file Web/js/app/controllers/mobile_map_manager.js

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1135]
@damirius @gsouvik 

Another conflict:
@damirius 's version: 
https://github.com/FWAJL/FieldWorkManager/blob/feature_damir/Web/js/app/controllers/mobile_map_manager.js

@gsouvik 's version:
https://github.com/FWAJL/FieldWorkManager/blob/feature_PM/Web/js/app/controllers/mobile_map_manager.js

At lines 762 to 775 (for Souvik) and at lines 711 to 724 (for Damir), the block of code conflicts. Do we need both or do we keep only the most recent (Damir's)?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL @damirius @gsouvik 

Keep Damir's Code.  Souvik was working on Issue #1079, but I realized that what his approach was not going to work in part because we had not properly set up the Location List (Issue #1075).  See my comment https://github.com/FWAJL/FieldWorkManager/issues/1079#issuecomment-126111138.

With my updated approach for Issue #1079 (https://github.com/FWAJL/FieldWorkManager/commit/55cfcfbb4c2daaa0c6532a9d153f3c7df581e04f), Souvik's code is deprecated.

**Comment by FWAJL** [comment]
@bsaiken  Ok!
