### ISSUE TITLE
Make field data uneditable by the PM in `/activetask/fieldData`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1150]

**Comment by FWAJL** [comment]
@bsaiken code on feature_PM branch.

**Comment by bsaiken** [comment]
@FWAJL 
I just edited these parameters. I logged out and logged back in to make sure the data was edited and saved into the database.

**Comment by WebDevJL** [comment]
@bsaiken 

I'm not able to edit the input field as a PM on the field data tab of an active task. See screenshot below:
![image 1](https://cloud.githubusercontent.com/assets/3506074/9250931/c5ce3308-41d0-11e5-9a31-401628faa247.png)

The code is on ***feature_PM***, not on dev branch. I have committed a new bug fix but on the inactive task ui (see note below).

@gsouvik @damirius: a note to you guys

Can you please use this check in the future on arrays because I have come a lot of cases where the variable is not empty but not an array and of course, the foreach loop will fail:

***Old code***
```
if(!empty($relation_data)) {
      foreach($relation_data as $relation) {
          // Do stuff...
      }
}
```
***New code***
```
if(!empty($relation_data) && is_array($relation_data)) {
      foreach($relation_data as $relation) {
          // Do stuff...
      }
}
```

**Comment by WebDevJL** [comment]
@gsouvik @damirius: updated note

Based on the PHP documentation, the following should suffice:

```
if(is_array($relation_data)) {
      foreach($relation_data as $relation) {
          // Do stuff...
      }
}
```

**Comment by bsaiken** [comment]
@WebDevJL 
You are correct - it is working now.
