### ISSUE TITLE
PM can attach a file in the `activetask/communications` tab.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1157]
PM could "send" a FT an attachment.  This is, I think, already enabled for Service Providers.

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

I wanted to finish this issue now, because I was already working on stuff in active_task.js so it was easier for me.
It's on feature_damir branch.

Also I noticed some bug with displaying task location form lists, we changed itemCategory value in db to task_location from task_location_id so script couldn't load any forms. This caused problems with displaying those lists on both forms tab and on "Attach task location form" list in communications tab. It should be solved now

**Comment by bsaiken** [comment]
@damirius 
I thought you might want to do this now, since you were in the midst.

This document attachment is working, and I was successfully able to see the document with my laptop.  However, I was not able to view the document with my mobile phone, using wither Safari or Chrome.  So, I will make a separate Issue for that.
