### ISSUE TITLE
Make attachments viewable by FTs at `mobile/communications`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1158]

**Comment by damirius** [comment]
@bsaiken 

Can you provide additional information? You don't see the link to the file or the link is broken? Also I think that you mentioned that you can't see it only on tablet/phone?

**Comment by bsaiken** [comment]
@damirius 
This works when  I test it on my desktop (using my computer to log into the /mobile/ UI.

On my iPhone, when I click on the link, the wheel starts turning, like it wants to download and view the doc, but it never completes the process no matter how long I wait.  Is it possible for FTs to view docs (png and pdf files)?  Perhaps not...

**Comment by damirius** [comment]
@bsaiken 

If your server is on desktop for example http://localhost/FWM and you access it over the phone through IP, for example http://192.168.1.32/FWM links will not work since they will show http://localhost/FWM/path_to_file.xxx, this will work on live since everyone will access the site over the same address.

Also yes FT can view all files, you said yourself that you opened them on your desktop while you were logged in as FT.

**Comment by bsaiken** [comment]
@damirius 
OK - I am closing this Issue since what I really need to do is unit test Issue #1157.
