### ISSUE TITLE
Display checklist at `/mobile/checklist`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1169]
At `/mobile/checklist`, display the checklist created in Issue #1167.  Hence, 1167 (and 1166) are  prerequisites.

One checklist item per line.

The FT can check (or uncheck) the checkbox.  A checked checkbox has  `task_checklist.ask_checklist_complete=1`

Checking or unchecking any box will automatically update the database.  I think this is a case where a direct query will be needed because the FT might check the box, then uncheck it again during the course of the field work.  

Because there may be a time delay communicating with the server, add a js behavior to disable other entries until the page is reloaded.

**Comment by WebDevJL** [comment]
> @bsaiken said:
> Because there may be a time delay communicating with the server, add a js behavior to disable other entries until the page is reloaded.

By disable other entries, do you mean checking other checkboxes, correct? If so, @damirius  I suggest disabling temporally all other checkboxes from the click event to the successful ajax response.

**Comment by bsaiken** [comment]
@damirius 
Yes, that is what I meant.

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

Added mobile/checklist.

Check it out on feature_damir branch.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I tried manually adding checklist entries to the database, but I was not successful.  This may be another one of those items where the most efficient way to test is to push to dev so I can use the create checkllist feature, which Souvik prepared, and the use checklist, which Damir prepared.  I also will need to see the checklist on my smartphone, so it needs to be merged with dev.

**Comment by bsaiken** [comment]
@FWAJL @damirius @gsouvik 
Not working for me.  I tried manually adding checklist items to the database, but nothing is displayed.  This may require #1167 to be completed before I can test.

**Comment by FWAJL** [comment]
@bsaiken @damirius Same issue as #1167 where the naming is wrong. 

The line 227 in the TaskChecklistController was:

`$manager = $this->managers()->getManagerOf("TaskCheckList");`

It should have been:

`$manager = $this->managers()->getManagerOf($this->module());`

A reminder: we usually name the Dal class after the controller, here "TaskChecklist" and that value is accessed via `$this->module()`. The goal of using OOP is very important in PHP because you can avoid these case where the error is silent and hard to stop (see comments of #1167).

I am committing and releasing the fix.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
This appears to work.  We'll know for certain when Issue #1170 is done.
