### ISSUE TITLE
Locations still innacurate

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1173]
See marked versus real coordiantes under the user baiken > Unit Testing > Cars in the lot

Location accuracy was better after I clicked the Target button in Google maps.

**Comment by bsaiken** [comment]
@damirius 
Please take a look at this...

**Comment by bsaiken** [comment]
@damirius 
Maybe this will help:
https://github.com/gwilson/getAccurateCurrentPosition

**Comment by damirius** [comment]
@bsaiken 

I've implemented geo.js extension for navigator and I've used his method instead of `getCurrentPosition`. Those default three options which we talked about before for caching and using best accuracy mode available are already set. There are 2 new options, `desiredAccuracy` and `maxWait`. `desiredAccuracy` is in meters, `maxWait` is in milliseconds. I used default values, 20m accuracy and maxWait of 15000ms. Since FTs will have to wait for 15s before getting their coordinates, I've added one inline block below mark button which will show estimated number of seconds before coordinates are loaded. Something like "Fetching coordinates: XXs".

You can see this implemented on location infowindows and task location infowindows on mobile/map for both marking and directions and on mobile/loc_list for marking locations/tasks and when adding new task location.

Like always commit is on feature_damir branch.

**Comment by bsaiken** [comment]
@damirius 
Can you merge this directly to the DEV branch.  Local testing, for this function, is not that meaningful.

**Comment by bsaiken** [comment]
@damirius 
Never mind - I merged to the DEV branch!  I'm sure Jeremie will be all over me about this.  However, that's really not what I need.  I need the DEV branch moved to Hurray Host so I can do Unit Testing in the field.  If you can do that for me, I can do unit testing.

**Comment by damirius** [comment]
@bsaiken 

Sorry I can't do that. I don't have any access parameters to do the pull on that server. We'll have to wait for Jeremie.

**Comment by bsaiken** [comment]
@damirius 
This is much better.  It was not consistent, but results are fairly good.  I will do more field testing to see if another Issue needs to be opened.
