### ISSUE TITLE
Improve coding efficiency with the FWM site - Step 2

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkManager#1192]
Step 2 is to automate the creation of a new url (controller, view, resources, routes).

@bsaiken do you mean to code that?

**Comment by bsaiken** [comment]
@WebDevJL 
I have no idea what this Issue is for.  Perhaps it would be best if you were to call things to my attention, and let me create the Issues, if i decide they are necessary.  Sometimes, I will ask you to do this, particularly if it requires some technical knowledge.  In the man time, focus on highest priority issues.  If you have nothing to do, I can assign you some of the existing Issues.
