### ISSUE TITLE
Suggestion: show a click-activated contextual menu to place location on a map

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkManager#1194]
@bsaiken 

Just an idea I had while placing locations on Google Maps.

What about implementing a tiny 2 items menu on the Project locations and Task locations map view when you click or tap (not a right click) a given location so that you can select either "View info" to popup the current prompt box or "Mark on map" to tell the site we want to place the location onto the map.

Here is a mockup:
![screen shot 2015-08-11 at 07 05 17](https://cloud.githubusercontent.com/assets/3506074/9190597/6b0abca0-3ff7-11e5-938b-a245647090fa.png)

**Comment by bsaiken** [comment]
@WebDevJL 
Good idea; however, clicking on the marker brings up the info window automatically, and "Place onto map" is one of the options, so there is no added functionality.  This option does not reduce the number of keystrokes.  Also, right clicking is not possible in the mobile maps, and it would be a worthwhile goal to make map functions uniform.  
It would be a better effort saving option, and more intuitive, if the PM could just drag and drop the marker onto the correct map location, but Damir was not able to pull it off.  
Also, following the Build, Measure, Learn, Model, the best approach now is for me to have beta testers using the site and making these kinds of suggestions.  In other words, if it works, don't fix it (unless someone asks us to).
I'd rather have you coding so that we can finish the existing Medium priority and above issues.  If beta testing happens at your end, I think Aurelie would be a good person to give feedback.  However, based on my current alpha testing, I am not ready to show this to anyone yet.

**Comment by FWAJL** [comment]
@bsaiken

Yes drag and drop is ideal. Let's wait for beta testing feedback.

Aurélie has been trained to the minimum and she has a pm account to carry
out some gardening project I suggested to her.
But yes it can wait for a few releases before fully using the webapp.
