### ISSUE TITLE
Milestone E (3) – Create the Data Collection page & (4) – Create a Notes page 

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#849]
Milestone E(3) – Create the Data Collection page.  
This page contains a list of Task Forms.  All forms are fillable pdf files.  This is the same list as the Project Manager page at url: http://dev.fieldworkmanager.com/active_task/forms.  

The forms shown on the list will have a clickable link, which will open the fillable pdf form.  

In some cases, in order to display the correct form list, a session variable $currentLocation must be set.  If the $currentLocation is not set, a popup prompt box will appear advising the FT to select their Location.  From the box, they have three options to set the $currentLocation.  
1) Provide a text box so the FT can enter the Location name.  We will add an autocomplete feature to this later.
2) navigate to the /locations/list page and select the Location.
3) navigate to the /map page and select their Location. 

When a Field Technician clicks a form, it will appear embedded on the page so that the FT can complete the form.   For this milestone, only embed the form on the page so it is viewable.

Milestone E(4) – Create a Notes page.    

This page contains a text field with the contents of task.task_instructions (not editable).
A separate textarea on the page will be for Task Notes.  The FT can record notes in this area.  The contents of the textarea [notes] shall be dynamically recorded in a table task_note where the columns will be task_note_id, task_id, task_note_category_type (technician_id) and task_note_category_value (id value of the category type).  You will need to request that this table be added to the database schema if not already available.

If $currentLocation is set, these notes include a prefix header “[Current Location Name]:”.  So, the field note “It’s hot today” would look like this: “MW-1: It’s hot today”.  If $currentLocation is not set, it’s a general note and has no prefix header.

All Notes are saved with a time and date stamp (recorded every time the submit button is clicked) and the identity of the FT.

**Comment by damirius** [comment]
@bsaiken
Video: https://drive.google.com/file/d/0B7Laiv0PjSvDb0h0d25YQkRPV3M/view?usp=sharing

Here is the notes page. Few things that I would like to mention. I don't know if we need to show notes from all users for this task or not. Currently I'm showing notes from all FTs and PM. I can restrict this only to logged in FT if needed. Other thing is that task_instructions could be displayed in a div, not a text field, since I suppose they will be probably more lengthy than this. Note that task_instructions are limited to 500 chars. 
Other than that, like you mentioned in the initial issue message I've implemented currentLocation, which is set by getItem Location Controller method. In other words clicking on the markers on the map currentLocation will be set. This way when we implement mobile/forms page for 'Data Collection', clicking on the marker then on 'Data Collection' button we will have currentLocation already set and ready to go so we don't need location popup or something like that. As far as the notes go, if currentLocation is set locations name will be added to the message text area.
I chose note to hide that first part of the message with locations name because currentLocation can't be unset, and if FT want to post a note without location name prefix he can just manually remove it and post a 'global' note.

Commit is pushed on feature_mobile branch, I've pulled your commit first, there were no conflicts. Also please run db update located in 2015-05-22.SQL.
"ALTER TABLE `task_note` ADD COLUMN `task_note_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER `task_note_value`;"

**Comment by bsaiken** [comment]
@damirius 
Let me clarify some details about notes.  Field Technicians are almost always required to keep notes while they are working.  It is part of the work record.  But, FTs do not need to see notes from the PM or any other FT.  Notes are for a single FT only.  So, in the Mobile UI, you do not need to specify who is creating the note - it is the logged-in FT by default.  PMs will be able to see the notes from all FTs, but we will not have time to sort and organize notes.  For now, it is enough to record them.

Notes are not associated with a Location - all notes are "global".  However, I do like your implementation that when a FT changes the current Location, that is recorded in the notes.  This also helps keep track of the work progress.  If you recall, back on Issue #974, we set up a record `task_location.task_location_status`.  So, when the FT (any FT) has the a Location set as their `currentLocation`, then `task_location_status==1`.  I noticed that the live site database has not yet been updated to include this data field.  

So, make these changes and I will do the function review.

**Comment by damirius** [comment]
@bsaiken

OK, I'll restrict the notes for Mobile UI only to show notes for logged in FT.
I notice that you mention live site database, I honestly have no idea about live site db, and I don't have any access to it.

**Comment by bsaiken** [comment]
@damirius 
The easiest fix for the live site database would be - when you get your own database updated to include all recent changes, send me the script for the entire new database, and I will update the live site (and my local site) to match yours.

**Comment by damirius** [comment]
@bsaiken

You can find latest version of my local db in Database\Scripts\Online-Backups\baiken_fwm_1_damir_20150522.sql

Also FT should see only his notes from now on on Mobile UI, but I left the option to fetch all notes for existing method if we need it later for PMs or whatever else.
Also everything is merged from feature_devsupport and feature_mobile into dev branch, and back again into feature_branches.

**Comment by bsaiken** [comment]
@damirius 
This is a double Issue.  We still need to be able to list and open location-forms from the FT mapping info window.  I mentioned this in  Issue #992, but it may have go lost in the sea of comments.

**Comment by damirius** [comment]
@bsaiken 

I thought we are doing separate popup or page for that, when clicking collect data button. I thought that gosuvik was on that since he worked with those forms :(

**Comment by bsaiken** [comment]
@damirius @gsouvik @FWAJL 
You are so right!  I forgot in the heat of the rush.
Souvik, I would like you to do this if you can.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL @damirius 
I've read the comments from the top and related thread, but still need a little help understanding the requirement. Could you please let me know how I can test this on my local branch. Do I have to login as a particular type of user. Where exactly this needs to be implemented, please provide any URL if possible.
Thank you

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
First, you will need to log in as a FT.  The FT UI should is updated on the DEV branch.  I do not think your feature branch should is updated.  Therefore, I suggest you checkout the feature_mobile bransh and work there.  

Several conditions need to be met for you to be able to access the correct page.  
First, you need to have added a Field technician so that they are added as a new user.  The email address is the username:password, so don't leave the field blank.
Then, you should be able to log in as a FT.

However...

Nothing will work unless the FT is assigned to a Task, and the Task is activated.  So, create a new Task and be sure to  assign your new FT to that Task.  
You need some Task Locations - make sure you add those.  You may need to add some Project Locations from the left menu first.  
You need to check the box on the `task/showForm` page that says "Task requires completion of a field form", then go the the Forms tab and add at least one form.  You should have some master forms to choose from since you have recently been working that feature.  If not, you can add a user form from the left hand menu.

Now the Task is all set up and you can Activate it.  

Then log in as your new FT.  If this is the only Task they are assigned to, you will be taken to the Map page.  If there are more than one Task, you will see the list of Tasks, so just choose one, but you need to land on the map page (`mobile/map`).

If you click on any of the Locations, you will see a button that says "Collect Data" - that will be your trigger.

![screen shot 2015-05-30 at 8 06 56 am](https://cloud.githubusercontent.com/assets/8228624/7897911/e1914c96-06a3-11e5-82e2-2487cc4b2484.png)

When the user clicks this button, they are given a list of the forms that were created during the Task Activation, but only list the form(s) for that specific Location.  There may only be one form (if there was only one Master or User form).  The Form title is clickable, and use fancybox to display the form.  Full screen mode would be best.

It's actually pretty simple, but there is a lot of set up.

**Comment by gsouvik** [comment]
@bsaiken 
Thank you for explaining in details. I followed the steps and was able to get to the task page when logged in as a technician. Here's how it looks
![screen shot 2015-05-30 at 10 15 11 pm](https://cloud.githubusercontent.com/assets/2292482/7898308/a75b9e3e-0719-11e5-8d25-d47fe47fcbe0.png)

But when I clicked on "Collect Data" I was presented with a page like this:
![screen shot 2015-05-30 at 10 15 27 pm](https://cloud.githubusercontent.com/assets/2292482/7898325/3b76413c-071a-11e5-82ad-bdfadc62317d.png)

Is it this screen, I would have to create? What would be it's structure like, would the forms be shown on a popup similar to the earlier screen or a list similar to the following:
![screen shot 2015-05-30 at 10 24 02 pm](https://cloud.githubusercontent.com/assets/2292482/7898344/da1f0c1a-071a-11e5-829b-44c3b7b368a9.png)

Just trying to gather the requirement so that I could translate it into code within the small time we are left with.

**Comment by bsaiken** [comment]
@gsouvik 
You are correct.  The "page" you see is just a place holder.  You do not actually need to create a page at all.  Just create a Popup Prompt box with the list of form(s) for this Location.  The forms listed in the Prompt Box shall have links to open the form.  

There should probably also be a popup alert box if there are no forms, or if the Location is "complete".  You will know the Location is "complete" by the value of `task_location.task_location_status`.  A value of "2" means the work at that Location is "complete".  See Issue #974 for more info on this if it's not clear.

**Comment by bsaiken** [comment]
@gsouvik 
Souvik,
This is a critical item for me using the site and showing to others (which is where I may generate the additional funds to continue), so I would like you to extend your eLance Job end date so you have time to finish this Issue.

**Comment by gsouvik** [comment]
@bsaiken 
Ok, shall do that.

**Comment by gsouvik** [comment]
@bsaiken 
The "task specific form" is now opened when the user clicks on "Collect Data" link.
1) Only the location specific forms are shown.
2) Clicking on the form, opens it using the fancybox.
3) If task is already completed, an alert box is shown.
4) If there are no forms available for this task, an alert box is shown.

Please review and let me know your feedback.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Is it possible to make the fancybox window full screen?

**Comment by gsouvik** [comment]
@bsaiken 
the Fancybox window now spans full screen, in the sense it takes up all the width and height which is available to it.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Excellent
