### ISSUE TITLE
Task COC requires Outside Resources checkbox

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#927]
When editing the Task COC, you need a service provider. Therefore the checkbox "Outside Resources required" should be automatically checked when checking "Submitting samples to a laboratory".

**Comment by bsaiken** [comment]
@FWAJL 
Actually, you don't need a service provider.  You need a lab, which is a type of service provider with a specific category (e.g. Labs).  This is a special case.  We could handle the selection of a lab on the COC form itself.  Let me think about this.

**Comment by WebDevJL** [comment]
@bsaiken 

Err... what you said is kinda of contradictory, isn't it? Anyhow, except if you have assigned service providers to a task and some of them are labs, the COC form data can't be saved. 

But now we have done forms, incl. the COC form as PDF, do we need this really and issue #558 ?

**Comment by bsaiken** [comment]
@FWAJL 
I'm surprised by your response.  If anyone were to understand the distinction, it would be someone who speaks computer language, which is necessarily precise.  Saying we need a Service Provider to collect filed samples for lab analysis is imprecise because we categorize service providers.  So, in this case, we can use the more precise language that we need a service provider with the category "Labs".  Since the service provider must have the category "Labs", we don't necessarily need to navigate to the more generic service providers tab.  

As far as using the PDF form - I had considered that.  There is a LOT of information that belongs on the PDF form that we have already collected.  But I don't think we are ready for that, and we would need software like pdftk (Mehedee) to make it work.  I'd like to get there, but it won't happen by the end of May, I am sure of that.

I will have decided by Friday.

**Comment by FWAJL** [comment]
@bsaiken 

Ok Brian. I will rephrase it: unless if you have assigned ***service providers of category "Labs"*** to a task and some of them are labs, the COC form data can't be saved.

I will wait for your answer tomorrow. Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
We forgot to talk about this...service provider (Lab) form entry value can't be null.  
But, for simplicity's sake, let's just remove the `Laboratory` select list from this form page.  The Lab can get saved on the Services tab.  

I realize that eventually we will need to add some code the validates a task when it is being promoted to become active, (e.g. verify a Lab has been selected if we are submitting samples to a lab), but let's not hang up progress here.

**Comment by bsaiken** [comment]
@WebDevJL 
I assigned this to you, but you could pass it on to Souvik....

**Comment by FWAJL** [comment]
@bsaiken 

I'm sorry I'm not explaining the problem properly.

This issue is related to #558.

We can NOT just remove the Lab select list. Why? Because the Task COC ***requires*** a service provider of category "Lab" which is a foregin key from table service in table task_coc. So by removing the select list, the Task COC data can NOT be saved.

So what you're wanting to have is to remove the foreign key on the task_coc table so a null is inserted in the service_id column for now. Please confirm that is what you want.

Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
Yes, removing the foreign key seems the easiest way to go.
